name: Tests

on:
  pull_request:
    branches:
      - main
      - sprint_3

jobs:
  test:
    if: ${{ !github.event.repository.private }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install bats
        uses: mig4/setup-bats@v1
        
      - name: Clone tests
        run: |
          rm -rf /tmp/tests-middle-frontend
          git clone https://github.com/Yandex-Practicum/tests-middle-frontend.git /tmp/tests-middle-frontend
          
      - name: Install dependencies
        run: npm install
        
      - name: Run typescript checks
        run: npx tsc --noEmit
        
      - name: Run stylelint
        run: npx stylelint "**/*.{css,scss}" --allow-empty-input
        
      - name: Run eslint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --max-warnings=0
        
      - name: Run tests
        run: bats --formatter pretty /tmp/tests-middle-frontend/tests/node_build.bats
        